### ISSUE TITLE
Possible to Provide machine.st source?

### ISSUE THREAD

**Issue by meteoricfarm** [hsainnos/LICSTER#20]
I'd like to replace PLC to my S7-1200.
Is it possible to provide source code belongs to machine.st?
then I can investigate PLC's behavior.

**Comment by mniedermaier** [comment]
Hello,

of course. The source code is already on Github (https://github.com/hsainnos/LICSTER/blob/master/devices/plc/data/machine.st). If you need further information let us know.

**Comment by kwansikkim** [comment]
Thanks for your help, I could solve the issue.
Punching Machine, S7-1200, HMI is up and running for now.

Thanks again.

**Comment by mniedermaier** [comment]
Hello kwansikkim,

this sounds awesome! Do you want to share your experience and contribute your solution to the GIT?

Thanks and regards

Matthias

**Comment by kwansikkim** [comment]
Sorry for the late response.
I'd love to contribute.
But one of my colleges is still working on it.
When integrating the task is done, I'll let you know.

**Comment by mniedermaier** [comment]
Hello @kwansikkim,

is there any update on the S7-1200 mitigation?
Thank you!

**Comment by kwansikkim** [comment]
Hello @mniedermaier 

My college is still working on it. 
He is not familiar with PLC like ladder logic and structured text, etc.
I will let you know as soon as it is done.

Sincerely,
Kwansik

**Comment by mniedermaier** [comment]
Closed due to inactivity. Feel free to reopen.
