### ISSUE TITLE
Gmail plaintext password in commit

### ISSUE THREAD

**Issue by dauthleikr** [hsainnos/LICSTER#36]
Hey, just wanted to let you know that the removed plaintext password in commit 781e163bef6809242ef7830a428afa538f8ec060 is still very visible, and draws attention because of `removed` and `password` being in the message. If the account is connected to anything I suggest changing the password if not done already ;)

**Comment by mniedermaier** [comment]
Hello @dauthleikr,

thank you very much for your hint :+1: Yes this was unintended to store the username and password of our test account in the GIT. We removed the credentials and also changed the password of the test account.
