### ISSUE TITLE
Update quantity of BOM x 2

### ISSUE THREAD

**Issue by minkione** [hsainnos/LICSTER#45]
Another thing. The mouser list of components... 
https://github.com/hsainnos/LICSTER/blob/master/devices/remote_io/README.md#component-ordering

Please update the quantity numbers (i.e. by multiplying by two).
When I placed the order I didn't notice was written that the components quantity was for ONE PCB only.
Now I just placed another one to get the missing parts.

I know the fault is on the reader... but still, better keep things simple.
Since at least 2 fully assembled PCB are needed anyway.

**Comment by mniedermaier** [comment]
Added total colum in https://github.com/hsainnos/LICSTER/commit/debff59780ff8e485cee798428d93360c085202b
