### ISSUE TITLE
OLED display doesn't work

### ISSUE THREAD

**Issue by space-maker** [hsainnos/LICSTER#49]
Hi, 
I joined the licster project to conclude my year of internship and I have a problem related to the pcb. 

I welded them correctly according to the pattern but after the flash of the smt from Windows 10, nothing happens. So I thought I had burned a circuit with welding. So I bought on jlcpcb but this time with pcbs already assembled.

I try to test with mutlimeter but anything seem correct so i asked your help about this problem.
Thanks for sharing this project, it is very interesting for what i do and i hope to achieve this before end of my internship.
![1](https://user-images.githubusercontent.com/52207552/105728409-6dc8ad80-5f2c-11eb-960a-d98fd2f895ae.jpg)
![3](https://user-images.githubusercontent.com/52207552/105728438-74efbb80-5f2c-11eb-8e86-832bcf4d701d.jpg)
![2](https://user-images.githubusercontent.com/52207552/105728445-75885200-5f2c-11eb-9670-1756354e068f.jpg)

**Comment by mniedermaier** [comment]
Hello and welcome to the LICSTER project.

I have seen, that you are using a STM32 F746. The default STM32, we are using for LICSTER is a STM32 by ST NUCLEO-F767ZI. I am not sure, if the same software will work out of the Box for the F746. 

What you can do/check:
- Does the blue LED blink?
- Can you ping the board on 192.168.0.50/51/52?
- Have you the possibility to test it with the F767?
- Change the software to use the F746? (STM32 CubeMX)

**Comment by space-maker** [comment]
Thank you for your prompt response. Damn it, how did I not notice that I had the wrong model 😅.

 I'm no longer at work for testing, but what I know is that:
 * blue LED doesn't blink
 * I try the ping and nothing happens
 * I recently ordered the F767ZI as you suggest. I will receive it tomorrow so I will keep you posted if it works

**Comment by mniedermaier** [comment]
Hi @space-maker,

I hope you have good news for me and the OLED works with the F767ZI?

**Comment by space-maker** [comment]
Hi,
I have not yet received the F767ZI as expected for today. I will give you news of my progress as soon as I have the right card for testing. 

I would like to know if you have any documentation to use correctly STM32 CubeMX. I will keep you informed of my progress. 
Have a good day

**Comment by space-maker** [comment]
Hi,

I'm pleased to announce that the screen is working ! Finally :) !

Thanks for the help. We just had to take the right model.
![works](https://user-images.githubusercontent.com/52207552/106116680-7a2e4f80-6152-11eb-948c-373521b72fb8.jpg)

**Comment by mniedermaier** [comment]
Happy to see the display working :) Please let us know your progress, and if you identify an other challenges during the set-up.
