### ISSUE TITLE
HMI webserver crashes when booting before PLC

### ISSUE THREAD

**Issue by saufel** [hsainnos/LICSTER#8]
The webserver boots quicker than the PLC. It then tries to open a connection to the PLC. Since that is not possible at that point, it simply crashes.

**Comment by saufel** [comment]
I fixed the issue. Now, the webserver starts regardless of the PLC. As long as it cannot open a connection to the PLC it shows DISCONNECTED as its state. I also added a Refresh button to refresh the page. The disconnected state does NOT disappear automatically once the connection is established. In future versions an more elegant version is planned.

**Comment by mniedermaier** [comment]
@saufel The HMI boots up, but does not connect after the network connection is available.
#9

**Comment by mniedermaier** [comment]
Fixed in both branches
